//
//  DomainRuleRegistry.swift
//  ReadabilityKit
//
//  Created by Chris Jenkins on 17/02/2026.
//

import Foundation

/// Registry of available domain-specific extraction rules.
///
/// The extractor queries this registry for URL-matching rules before candidate selection.
/// Matching rules can provide:
/// - a preferred content root (`preferRules` mode),
/// - candidate score hints (`rulesAsHints` mode),
/// - metadata overrides.
struct DomainRuleRegistry: Sendable {
    /// Built-in rule set used by ``ReadabilityExtractor``.
    static let `default` = DomainRuleRegistry(
        rules: DomainRuleRegistry.customGeneratedRules
    )

    /// Auto-generated rule set derived from `Tests/ReadabilityKitTests/Custom/**/index.js`.
    static let customGeneratedRules: [any DomainExtractionRule] = [
        D247sportsComCustomDomainExtractionRule(),
        AbcnewsGoComCustomDomainExtractionRule(),
        ArstechnicaComCustomDomainExtractionRule(),
        BBCDomainExtractionRule(),
        BiorxivOrgCustomDomainExtractionRule(),
        BlisterreviewComCustomDomainExtractionRule(),
        BlogspotComCustomDomainExtractionRule(),
        BookwalkerJpCustomDomainExtractionRule(),
        BuzzapJpCustomDomainExtractionRule(),
        ClinicaltrialsGovCustomDomainExtractionRule(),
        DeadlineComCustomDomainExtractionRule(),
        DeadspinComCustomDomainExtractionRule(),
        EpaperZeitDeCustomDomainExtractionRule(),
        FandomWikiaComCustomDomainExtractionRule(),
        FortuneComCustomDomainExtractionRule(),
        ForwardComCustomDomainExtractionRule(),
        GeniusComCustomDomainExtractionRule(),
        GetnewsJpCustomDomainExtractionRule(),
        GithubComCustomDomainExtractionRule(),
        GothamistComCustomDomainExtractionRule(),
        HellogigglesComCustomDomainExtractionRule(),
        IciRadioCanadaCaCustomDomainExtractionRule(),
        JapanCNETComCustomDomainExtractionRule(),
        JapanZdnetComCustomDomainExtractionRule(),
        JvndbJVNJpCustomDomainExtractionRule(),
        MaTtiasBeCustomDomainExtractionRule(),
        MashableComCustomDomainExtractionRule(),
        MediumComCustomDomainExtractionRule(),
        MoneyCNNComCustomDomainExtractionRule(),
        NewrepublicComCustomDomainExtractionRule(),
        NewsMynaviJpCustomDomainExtractionRule(),
        NewsNationalgeographicComCustomDomainExtractionRule(),
        NymagComCustomDomainExtractionRule(),
        ObamawhitehouseArchivesGovCustomDomainExtractionRule(),
        ObserverComCustomDomainExtractionRule(),
        OtrsComCustomDomainExtractionRule(),
        PagesixComCustomDomainExtractionRule(),
        PastebinComCustomDomainExtractionRule(),
        PeopleComCustomDomainExtractionRule(),
        PhpspotOrgCustomDomainExtractionRule(),
        PitchforkComCustomDomainExtractionRule(),
        PostlightComCustomDomainExtractionRule(),
        QzComCustomDomainExtractionRule(),
        ScanNetsecurityNeJpCustomDomainExtractionRule(),
        ScienceflyComCustomDomainExtractionRule(),
        SectIijAdJpCustomDomainExtractionRule(),
        TakagiHiromitsuJpCustomDomainExtractionRule(),
        TechlogIijAdJpCustomDomainExtractionRule(),
        ThefederalistpapersOrgCustomDomainExtractionRule(),
        ThoughtcatalogComCustomDomainExtractionRule(),
        TimesofindiaIndiatimesComCustomDomainExtractionRule(),
        TwitterComCustomDomainExtractionRule(),
        UproxxComCustomDomainExtractionRule(),
        WeeklyAsciiJpCustomDomainExtractionRule(),
        WikipediaOrgCustomDomainExtractionRule(),
        WiredJpCustomDomainExtractionRule(),
        AbendblattDeCustomDomainExtractionRule(),
        AlComCustomDomainExtractionRule(),
        AmericanowComCustomDomainExtractionRule(),
        AndroidcentralComCustomDomainExtractionRule(),
        AOLComCustomDomainExtractionRule(),
        ApartmenttherapyComCustomDomainExtractionRule(),
        AsahiComCustomDomainExtractionRule(),
        BloombergComCustomDomainExtractionRule(),
        BroadwayworldComCustomDomainExtractionRule(),
        BustleComCustomDomainExtractionRule(),
        BuzzfeedComCustomDomainExtractionRule(),
        CBCCaCustomDomainExtractionRule(),
        CbssportsComCustomDomainExtractionRule(),
        ChicagotribuneComCustomDomainExtractionRule(),
        CNBCComCustomDomainExtractionRule(),
        CNETComCustomDomainExtractionRule(),
        CNNComCustomDomainExtractionRule(),
        DmagazineComCustomDomainExtractionRule(),
        ElecomCoJpCustomDomainExtractionRule(),
        EngadgetComCustomDomainExtractionRule(),
        EonlineComCustomDomainExtractionRule(),
        FastcompanyComCustomDomainExtractionRule(),
        FoolComCustomDomainExtractionRule(),
        FortinetComCustomDomainExtractionRule(),
        GizmodoJpCustomDomainExtractionRule(),
        GrueneDeCustomDomainExtractionRule(),
        HuffingtonpostComCustomDomainExtractionRule(),
        InfoqComCustomDomainExtractionRule(),
        InquisitrComCustomDomainExtractionRule(),
        InvestmentexecutiveComCustomDomainExtractionRule(),
        IpaGoJpCustomDomainExtractionRule(),
        ItmediaCoJpCustomDomainExtractionRule(),
        JnsaOrgCustomDomainExtractionRule(),
        LadbibleComCustomDomainExtractionRule(),
        LatimesComCustomDomainExtractionRule(),
        LemondeFrCustomDomainExtractionRule(),
        LifehackerJpCustomDomainExtractionRule(),
        LinkedinComCustomDomainExtractionRule(),
        LittlethingsComCustomDomainExtractionRule(),
        MacrumorsComCustomDomainExtractionRule(),
        MentalflossComCustomDomainExtractionRule(),
        MiamiheraldComCustomDomainExtractionRule(),
        MoongiftJpCustomDomainExtractionRule(),
        MsnComCustomDomainExtractionRule(),
        MsnbcComCustomDomainExtractionRule(),
        NationalgeographicComCustomDomainExtractionRule(),
        NbcnewsComCustomDomainExtractionRule(),
        NDTVComCustomDomainExtractionRule(),
        NewyorkerComCustomDomainExtractionRule(),
        NPROrgCustomDomainExtractionRule(),
        NydailynewsComCustomDomainExtractionRule(),
        NytimesComCustomDomainExtractionRule(),
        OpposingviewsComCustomDomainExtractionRule(),
        OreillyCoJpCustomDomainExtractionRule(),
        OssnewsJpCustomDomainExtractionRule(),
        PhoronixComCustomDomainExtractionRule(),
        PoliticoComCustomDomainExtractionRule(),
        PopsugarComCustomDomainExtractionRule(),
        ProspectmagazineCoUkCustomDomainExtractionRule(),
        Publickey1JpCustomDomainExtractionRule(),
        QdailyComCustomDomainExtractionRule(),
        RawstoryComCustomDomainExtractionRule(),
        RbbtodayComCustomDomainExtractionRule(),
        RecodeNetCustomDomainExtractionRule(),
        RedditComCustomDomainExtractionRule(),
        Refinery29ComCustomDomainExtractionRule(),
        ReutersComCustomDomainExtractionRule(),
        RollingstoneComCustomDomainExtractionRule(),
        SanwaCoJpCustomDomainExtractionRule(),
        SbnationComCustomDomainExtractionRule(),
        SiComCustomDomainExtractionRule(),
        SlateComCustomDomainExtractionRule(),
        SpektrumDeCustomDomainExtractionRule(),
        TheatlanticComCustomDomainExtractionRule(),
        TheguardianComCustomDomainExtractionRule(),
        ThepennyhoarderComCustomDomainExtractionRule(),
        ThepoliticalinsiderComCustomDomainExtractionRule(),
        ThevergeComCustomDomainExtractionRule(),
        TMZComCustomDomainExtractionRule(),
        TodayComCustomDomainExtractionRule(),
        UsmagazineComCustomDomainExtractionRule(),
        VoxComCustomDomainExtractionRule(),
        WashingtonpostComCustomDomainExtractionRule(),
        WesternjournalismComCustomDomainExtractionRule(),
        WiredComCustomDomainExtractionRule(),
        YahooComCustomDomainExtractionRule(),
        YomiuriCoJpCustomDomainExtractionRule(),
        YoutubeComCustomDomainExtractionRule(),
    ]

    /// Ordered rules; earlier rules win for preferred-root selection.
    let rules: [any DomainExtractionRule]

    /// Returns all rules that match the provided source URL.
    /// - Parameter url: Source article URL.
    func matchingRules(for url: URL) -> [any DomainExtractionRule] {
        rules.filter { $0.matches(url: url) }
    }
}
